### PR TITLE
Fix bad-param of hasSubscribed judge for CRDWatcher

### LINKED ISSUE #35: [BUG] CRDWatcher does not correctly match AppName when processing CRD resources
## Issue Description

Type: *bug report*
Regarding the code below:

```go
//This method requires an AppName as a parameter
func (r *CRDWatcher) HasAnySubscribedOfApp(app string) bool {
	r.updateMux.RLock()
	defer r.updateMux.RUnlock()

	_, exist := r.subscribedApps[app]
	return exist
}

func (r *CRDWatcher) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
        //The actual parameter here is a namespace rather than an AppName
	if r.HasAnySubscribedOfApp(req.Namespace) {
		// Ignore unmatched namespace
		return ctrl.Result{Requeue: false, RequeueAfter: 0}, nil
	}
        //...
}
```

### Describe what you expected to happen

`HasAnySubscribedOfApp` should correctly match the App

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Anything else we need to know?

### PR DESCRIPTION
**Pull request by YunWZ**
### Describe what this PR does / why we need it

fix bug #35 , We should check the namespace first instead of the app name；And only namespaced applications can uniquely identify an application。

### Does this pull request fix one issue?

Fixes #35 

### Special notes for reviews

### CODE REVIEW

**Comment by sczyh30** [comment]
Could you please add some PR description?

File: pkg/model/model.go [hunk 1]
```diff
@@ -16,13 +16,18 @@ package model
...
 
 type NamespacedApp struct {
 	Namespace string
 	App       string
 }
 
+func (st NamespacedApp) String() string {
+	return st.Namespace + string(types.Separator) + st.Namespace
+}
+
```
Comment (jnan806) [inline pkg/model/model.go:30]: 1. func is used.   
2. Namespace is double printed.
3. maybe use join str with json format is better.

File: pkg/model/subscribe.go [hunk 2]
```diff
@@ -22,9 +22,7 @@ type LabelKV struct {
 type SubscribeKind = string
 
 type SubscribeTarget struct {
-	Namespace string
-	// AppName represents the target app name. Fast path for "app" label.
-	AppName string
+	NamespacedApp NamespacedApp
 	//Labels  []LabelKV
 	Kind SubscribeKind
 }
```
Comment (jnan806) [inline pkg/model/subscribe.go:28]: The original code is more suitable, it can match with definition in proto:

``` proto
message SubscribeRequestTarget {
  string namespace = 1;
  string app = 2;
  repeated SubscribeLabelKV labels = 3;
  repeated string kinds = 4;
}
```

Comment (jnan806) [inline pkg/model/subscribe.go:28]: The original code is more suitable, it can match with definition in proto:

``` proto
message SubscribeRequestTarget {
  string namespace = 1;
  string app = 2;
  repeated SubscribeLabelKV labels = 3;
  repeated string kinds = 4;
}
```

**Review by jnan806 — APPROVED** [review]
LGTM ~  Thanks !
